### ISSUE TITLE
Active brightness in Lovelace Light when off

### ISSUE THREAD

**Issue by Molodax** [dr1rrb/ha-twinkly#1]
First, thanks for this integration and Happy New Year!
I've just noticed that when Twinkly is off, the brightness sider is still active in standard Lovelace light element. Not sure whether it is intentional, however, sliders for all my other lights set at 0 when they are off.

**Comment by dr1rrb** [comment]
Hi, thanks and happy new year too :)

It's not intentional at all, it's probably because the Twinkly seems to have a feature to disable the brightness. For instance, if you request to set the brightness to 0, it will actually goes to full brightness. I had to explicitly request a "off" in that case.

What's weird is that I don't have the behavior you described on my side:
![TwinklyBrigthnessOff](https://user-images.githubusercontent.com/8635919/71643159-b4919880-2c83-11ea-8803-399023772be7.gif) 

I however just did a fix for that : https://github.com/dr1rrb/ha-twinkly/commit/18b93ca104df744d4712f84dbfeaa68fee89526b Since it was useless to make an API to get the brightness while the device is off, I hard-coded it to 0, so it should also fix your issue.

**Comment by Molodax** [comment]
The issue with brightness slider was when I used Light card (the rounded slider on the card), however, you resolved it with the latest update.
Thank you.
